# Generated by Django 4.1.1 on 2022-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
